# Generated by Django 3.1.7 on 2021-07-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to='users.member')),
                ('rated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_to', to='users.member')),
            ],
            options={
                'unique_together': {('rated_by', 'rated_to')},
            },
        ),
    ]
