# Generated by Django 3.1.7 on 2021-07-30 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import products.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, storage=gdstorage.storage.GoogleDriveStorage, upload_to=products.models.image_directory_path)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('fresh_upto', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact_no', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1111111111)])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.city')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_by', to='users.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_orders', to='products.post')),
            ],
            options={
                'unique_together': {('ordered_by', 'post')},
            },
        ),
    ]
