# Generated by Django 3.1.7 on 2021-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210314_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
